In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [ ]:
x=np.array([[2,3],[3,4],[6,6],[7,7]])
k_means=KMeans(n_clusters=2, random_state=0, n_init="auto")

In [ ]:
k_means.fit(x)

KMeans(n_clusters=2, random_state=0)

In [ ]:
k_means.labels_

array([1, 1, 0, 0], dtype=int32)

In [ ]:
values=k_means.predict([[2,3], [6,6]])

In [ ]:
values

array([1, 0], dtype=int32)

In [ ]:
k_means.cluster_centers_

array([[6.5, 6.5],
       [2.5, 3.5]])

In [ ]:
clusters = {}
for i, label in enumerate(k_means.labels_):
    if label not in clusters:
        clusters[label] = []
    clusters[label].append(x[i])

for label, points in clusters.items():
    print(f"Cluster {label+1}: {points}")

Cluster 2: [array([2, 3]), array([3, 4])]
Cluster 1: [array([6, 6]), array([7, 7])]


In [ ]:
x1=np.array([2,4,10,12,3,20,30,11,25])

In [ ]:
k_means1=KMeans(n_clusters=2, random_state=0, n_init="auto")
k_means1.fit(x1.reshape(-1,1))

KMeans(n_clusters=2, random_state=0)

In [ ]:
pred=k_means1.predict([[2],[20]])
pred

array([0, 1], dtype=int32)

In [ ]:
k_means1.cluster_centers_

array([[ 7.],
       [25.]])

In [ ]:
k_means1.labels_

array([0, 0, 0, 0, 0, 1, 1, 0, 1], dtype=int32)

In [ ]:
clusters1 = {}
for i, label1 in enumerate(k_means1.labels_):
    if label1 not in clusters1:
        clusters1[label1] = []
    clusters1[label1].append(x1[i])

for label1, points in clusters1.items():
    print(f"Cluster {label1}: {points}")

Cluster 0: [np.int64(2), np.int64(4), np.int64(10), np.int64(12), np.int64(3), np.int64(11)]
Cluster 1: [np.int64(20), np.int64(30), np.int64(25)]
